name = "SymbolicTensors2"
uuid = "d43927f5-205c-445e-8481-fceb12a04410"
authors = ["miguelraz <miguelraz@ciencias.unam.mx> and contributors"]
version = "0.1.0"

[deps]
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
SymbolicUtils = "0.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
